### ISSUE TITLE
Fix demo link on repo

### ISSUE THREAD

**Issue by karlhorky** [conorhastings/react-syntax-highlighter#186]
Hey, quick fix:

Link on Repo (redirects to [your homepage](https://conorhastings.github.io/)):
http://conor.rodeo/react-syntax-highlighter/demo/

Correct link:
https://conorhastings.github.io/react-syntax-highlighter/demo/

Would do a PR, but GitHub doesn't allow this yet.

**Comment by conorhastings** [comment]
this has been addressed, thank you.

**Comment by karlhorky** [comment]
Hm, still doesn't work for me. To be clear, I mean the link next to the description of the repo:

![Screenshot_20190715-080735](https://user-images.githubusercontent.com/1935696/61197960-c54f5180-a6d7-11e9-84d0-ea54958036eb.png)

**Comment by conorhastings** [comment]
misunderstood should work now

**Comment by karlhorky** [comment]
Cheers, works!
