### ISSUE TITLE
Disable syntax highlighting

### ISSUE THREAD

**Issue by 1999** [conorhastings/react-syntax-highlighter#87]
First of all thank you for react-syntax-highlighter. We use it in [atlaskit](https://bitbucket.org/atlassian/atlaskit/src/master/packages/code/src/Code.tsx?fileviewer=file-view-default) library and it's great!

There's an issue which we're still missing in react-syntax-highlighter: disable syntax highlighting. It looks like lowlight.js is also missing this feature while highlight.js supports this through [classnames](https://github.com/isagalaev/highlight.js/blob/master/README.md#getting-started).

I looked into into react-syntax-highlighter code and didn't find an easy way to do this. In our code the easiest way to do this is to do a manual check and mimic react-syntax-highlight HTML layout on our part:

![image](https://user-images.githubusercontent.com/73191/32033156-a4be70d2-ba56-11e7-8095-85222785b4e1.png)

But it would be great to have "text" language support in react-syntax-highlighter

**Comment by conorhastings** [comment]
but i've published `v5.8.0` which allows passings `text` as a language.

Thanks for the issue!

**Comment by 1999** [comment]
@conorhastings hm, it's still missing here: https://github.com/conorhastings/react-syntax-highlighter/blob/master/AVAILABLE_LANGUAGES.MD

**Comment by conorhastings** [comment]
@1999 it is I've implemented a more complete solution and pushed a patch . It won't show up here --  https://github.com/conorhastings/react-syntax-highlighter/blob/master/AVAILABLE_LANGUAGES.MD -- because this is a list of importable language syntaxes which text is not, i've made a not in the language section of the readme though. Thanks for the feedback

published `v5.8.1` if you want to check that out
